/* Lexicon League V2 — two divisions, promotion/relegation and cups */
const LL_V2_SAVE_KEY='lexicon_league_save_v2';
const LL_FIRST_TEAMS=[
  {name:'Antalyaspor',short:'ANT',stars:3,icon:'🔴',logo:'https://tmssl.akamaized.net/images/wappen/head/589.png'},
  {name:'Bursaspor',short:'BUR',stars:3,icon:'🐊',logo:'https://tmssl.akamaized.net/images/wappen/head/20.png'},
  {name:'Bodrum FK',short:'BDR',stars:3,icon:'🌊',logo:'https://tmssl.akamaized.net/images/wappen/head/44006.png'},
  {name:'Kayserispor',short:'KAY',stars:3,icon:'🟡',logo:'https://tmssl.akamaized.net/images/wappen/head/3205.png'},
  {name:'Sivasspor',short:'SİV',stars:3,icon:'🔴',logo:'https://tmssl.akamaized.net/images/wappen/head/2381.png'},
  {name:'Fatih Karagümrük',short:'FKG',stars:3,icon:'⚫',logo:'https://tmssl.akamaized.net/images/wappen/head/6646.png'},
  {name:'Manisa FK',short:'MAN',stars:2,icon:'⚫',logo:'https://tmssl.akamaized.net/images/wappen/head/48913.png'},
  {name:'Iğdır FK',short:'IĞD',stars:2,icon:'🟢',logo:'https://tmssl.akamaized.net/images/wappen/head/74664.png'},
  {name:'İstanbulspor',short:'İST',stars:2,icon:'🟡',logo:'https://tmssl.akamaized.net/images/wappen/head/924.png'},
  {name:'Bandırmaspor',short:'BAN',stars:2,icon:'🟣',logo:'https://tmssl.akamaized.net/images/wappen/head/20760.png'},
  {name:'Batman Petrolspor',short:'BAT',stars:2,icon:'🟢',logo:'https://tmssl.akamaized.net/images/wappen/head/3211.png'},
  {name:'Pendikspor',short:'PEN',stars:2,icon:'🔴',logo:'https://tmssl.akamaized.net/images/wappen/head/3209.png'},
  {name:'Van Spor FK',short:'VAN',stars:2,icon:'🔵',logo:'https://tmssl.akamaized.net/images/wappen/head/3173.png'},
  {name:'Ankara Keçiörengücü',short:'KEÇ',stars:2,icon:'🟣',logo:'https://tmssl.akamaized.net/images/wappen/head/12388.png'},
  {name:'Sarıyerspor',short:'SAR',stars:1,icon:'⚪',logo:'https://tmssl.akamaized.net/images/wappen/head/518.png'},
  {name:'Esenler Erokspor',short:'ERO',stars:1,icon:'🟢',logo:'https://tmssl.akamaized.net/images/wappen/head/45269.png'},
  {name:'Ümraniyespor',short:'ÜMR',stars:1,icon:'🔴',logo:'https://tmssl.akamaized.net/images/wappen/head/24245.png'},
  {name:'Mardin 1969 Spor',short:'MAR',stars:1,icon:'🔴',logo:'https://tmssl.akamaized.net/images/wappen/head/68377.png'},
  {name:'Muğlaspor',short:'MUĞ',stars:1,icon:'🟢',logo:'https://tmssl.akamaized.net/images/wappen/head/2378.png'},
  {name:'Boluspor',short:'BOL',stars:2,icon:'🔴',logo:'https://tmssl.akamaized.net/images/wappen/head/3207.png'}
];
const LL_SUPER_STAR_MAP={Galatasaray:5,'Fenerbahçe':5,'Beşiktaş':4,Trabzonspor:4,'Başakşehir':3,Konyaspor:3,Alanyaspor:3,'Kasımpaşa':3,'Göztepe':3,Samsunspor:3,'Ç. Rizespor':3,Eyüpspor:3,'Amed SK':2,'Çorum FK':2,'Erzurumspor FK':2,'Gaziantep FK':2,'Gençlerbirliği':2,Kocaelispor:2};
LL_TEAMS.forEach(t=>t.stars=LL_SUPER_STAR_MAP[t.name]||2);
const LL_ALL_TEAMS=[...LL_TEAMS,...LL_FIRST_TEAMS];
const LL_COMP_REWARDS={league:{ap:5,win:50,draw:20,loss:5},cup:{ap:5,win:60,draw:20,loss:8},playoff:{ap:5,win:60,draw:20,loss:8},ucl:{ap:7,win:90,draw:40,loss:15},uel:{ap:7,win:85,draw:35,loss:12},uecl:{ap:6,win:80,draw:30,loss:10}};
const LL_CUP_WEEKS=[3,8,14,20,26,32],LL_EURO_WEEKS=[5,11,17,23,29];
const LL_CUP_ROUNDS=['1. Tur','Son 32','Son 16','Çeyrek Final','Yarı Final','Final'];
const LL_EURO_ROUNDS=['Son 32','Son 16','Çeyrek Final','Yarı Final','Final'];
const LL_EURO_LOGO_IDS={
  'Paris Saint-Germain':583,'Real Madrid':418,'Manchester City':281,'Bayern München':27,Liverpool:31,Inter:46,Chelsea:631,'Borussia Dortmund':16,Barcelona:131,Arsenal:11,'Bayer Leverkusen':15,'Atlético Madrid':13,Benfica:294,Atalanta:800,Villarreal:1050,Juventus:506,'Eintracht Frankfurt':24,'Club Brugge':2282,'Tottenham Hotspur':148,'PSV Eindhoven':383,Ajax:610,Napoli:6195,'Sporting CP':336,Olympiacos:683,Marseille:244,Copenhagen:190,Monaco:162,Galatasaray:141,'Union Saint-Gilloise':3948,'Qarabağ':10625,'Athletic Club':621,'Newcastle United':762,'Bodø/Glimt':2619,'Slavia Praha':62,Pafos:20401,'Kairat Almaty':10470
};

function llTeamDef(name){
  const domestic=LL_ALL_TEAMS.find(t=>t.name===name);if(domestic)return domestic;
  const euro=UCL_TEAMS.find(t=>t.name===name),logoId=LL_EURO_LOGO_IDS[name];return euro?{name:euro.name,short:euro.short,stars:euro.pot===1?5:euro.pot===2?4:3,icon:euro.flag,logo:logoId?`https://tmssl.akamaized.net/images/wappen/head/${logoId}.png`:''}:{name,short:name,stars:3,icon:'🌍',logo:''};
}
function llTeamLogo(teamOrName,variant=''){
  const team=typeof teamOrName==='string'?llTeamDef(teamOrName):teamOrName;if(!team)return '';
  if(!team.logo)return `<span class="ll-team-logo-fallback" style="display:inline-flex">${team.icon||'⚽'}</span>`;
  return `<img class="ll-team-logo ${variant}" src="${team.logo}" alt="${llEscape(team.name)} logosu" onerror="this.style.display='none';this.nextElementSibling.style.display='inline-flex'"><span class="ll-team-logo-fallback">${team.icon||'⚽'}</span>`;
}
function llRange(stars){return stars<=1?[1,4]:stars===2?[1,5]:stars===3?[2,6]:stars===4?[3,6]:[4,6];}
function llRangeText(stars){const [a,b]=llRange(stars);return `${a}-${b}`;}
function llStars(n){return '⭐'.repeat(n);}
function llTeamLeague(name){const s=lexLeague.state;if(s?.leagues?.super?.includes(name))return 'super';if(s?.leagues?.first?.includes(name))return 'first';return null;}
function llLeagueLabel(key){return key==='super'?'Süper Lig':'TFF 1. Lig';}
function llBlankStandings(names){return Object.fromEntries(names.map(n=>[n,llBlankStanding(n)]));}
function llNewState(teamName){
  const teams={};LL_ALL_TEAMS.forEach(t=>teams[t.name]={name:t.name,stars:t.stars,cards:{'Kaleci':null,'Orta Saha':null,'Forvet':null},lastResults:[],wins:0,lockedDice:{},aiAp:0,nextMatchRerolls:0,sixStreaks:{},nextMatchBonuses:{}});
  const superNames=LL_TEAMS.map(t=>t.name),firstNames=LL_FIRST_TEAMS.map(t=>t.name);
  const state={version:2,season:1,week:1,playerTeam:teamName,ap:0,lp:0,teams,leagues:{super:superNames,first:firstNames},standings:{super:llBlankStandings(superNames),first:llBlankStandings(firstNames)},schedules:{super:llGenerateSchedule(superNames),first:llGenerateSchedule(firstNames)},results:[],usedWords:[],transferWindowsVisited:{},aiTransferWindows:{},aiShopVersion:2,starterPackClaimed:false,starterAiAssigned:false,starterOffers:{},seasonEnded:false,lastSeasonSummary:null,pendingFixture:null,playoff:null,europe:null,trophies:[],createdAt:new Date().toISOString()};
  llV2InitCup(state);return state;
}
function llSave(){if(lexLeague.state)localStorage.setItem(LL_V2_SAVE_KEY,JSON.stringify(lexLeague.state));}
function llLoad(){try{const s=JSON.parse(localStorage.getItem(LL_V2_SAVE_KEY)||'null');return s?.version===2?s:null;}catch{return null;}}
function llResetGame(){if(!confirm('İki ligli kariyer kaydı tamamen silinsin mi?'))return;localStorage.removeItem(LL_V2_SAVE_KEY);lexLeague.state=null;llClearTransient();renderLexiconLeagueLanding();}
function llContinueGame(){const s=llLoad();if(!s){llRenderTeamSelect();return;}lexLeague.state=s;lexLeague.active=true;llSetWide(true);if(!s.starterPackClaimed)llRenderStarterShop();else if(s.seasonEnded)llRenderSeasonEnd();else llRenderDashboard();}
function llRenderTeamSelect(){lexLeague.active=true;llSetWide(true);llArea().innerHTML=`<div class="ll-shell"><div class="ll-panel"><div class="ll-topbar"><div><div class="ll-title">TFF 1. Lig'den <em>Başla</em></div><div class="ll-muted">20 kulüp · 5 yıldızlı yeni güç sistemi · Hedef Süper Lig</div></div><button class="ll-btn" onclick="renderLexiconLeagueLanding()">← Geri</button></div><div class="ll-team-grid">${LL_FIRST_TEAMS.map(t=>`<button class="ll-team-option" onclick="llStartCareer('${llEscape(t.name)}')"><div class="ll-team-name team-with-logo">${llTeamLogo(t,'compact')}<span>${llEscape(t.name)}</span></div><div class="ll-stars">${llStars(t.stars)}</div><div class="ll-range">Zar aralığı ${llRangeText(t.stars)}</div></button>`).join('')}</div></div></div>`;}
function llAssignStarterCardsToAi(){const s=lexLeague.state;if(!s||s.starterAiAssigned)return;LL_ALL_TEAMS.map(t=>t.name).filter(n=>n!==s.playerTeam).forEach(llAssignAiCard);s.starterAiAssigned=true;}
function llHeldCardIds(){const ids=new Set();Object.values(lexLeague.state.teams).forEach(t=>LL_POSITIONS.forEach(p=>{if(t.cards?.[p])ids.add(t.cards[p]);}));return ids;}

function llSortTable(key=llTeamLeague(lexLeague.state.playerTeam)||'first'){return Object.values(lexLeague.state.standings[key]).sort((a,b)=>b.Pts-a.Pts||b.GD-a.GD||b.GF-a.GF||a.team.localeCompare(b.team,'tr'));}
function llUpdateStanding(team,gf,ga){const key=llTeamLeague(team),r=lexLeague.state.standings[key][team];r.P++;r.GF+=gf;r.GA+=ga;r.GD=r.GF-r.GA;if(gf>ga){r.W++;r.Pts+=3;}else if(gf===ga){r.D++;r.Pts++;}else r.L++;const ts=llTeamState(team);ts.lastResults.push(gf>ga?'W':gf===ga?'D':'L');ts.lastResults=ts.lastResults.slice(-5);if(gf>ga)ts.wins++;}
function llPlayerFixture(){const s=lexLeague.state;if(s.pendingFixture)return s.pendingFixture;const key=llTeamLeague(s.playerTeam),round=s.schedules[key][s.week-1]||[];const f=round.find(x=>x.home===s.playerTeam||x.away===s.playerTeam);return f?{...f,competition:'league',league:key,roundLabel:`${s.week}. Hafta`}:null;}
function llCurrentRound(key=llTeamLeague(lexLeague.state.playerTeam)){return lexLeague.state.schedules[key]?.[lexLeague.state.week-1]||[];}
function llTableHtml(key=llTeamLeague(lexLeague.state.playerTeam)||'first'){
  const rows=llSortTable(key);return `<div class="ll-table-wrap"><table class="ll-table"><thead><tr><th>#</th><th>Takım</th><th>O</th><th>G</th><th>B</th><th>M</th><th>AG</th><th>YG</th><th>AV</th><th>Kart</th><th>AI AP</th><th>P</th></tr></thead><tbody>${rows.map((r,i)=>{const t=llTeamState(r.team),cards=LL_POSITIONS.filter(p=>t.cards[p]).length;return `<tr class="${r.team===lexLeague.state.playerTeam?'player ':''}${key==='first'&&i<2?'champion-zone ':''}${key==='super'&&i>=rows.length-3?'relegation-zone ':''}"><td>${i+1}</td><td>${llTeamLogo(r.team,'table')}${llEscape(r.team)} <span class="ll-stars">${llStars(t.stars)}</span></td><td>${r.P}</td><td>${r.W}</td><td>${r.D}</td><td>${r.L}</td><td>${r.GF}</td><td>${r.GA}</td><td>${r.GD}</td><td>${cards}/3</td><td>${r.team===lexLeague.state.playerTeam?'—':Math.floor(t.aiAp||0)}</td><td><b>${r.Pts}</b></td></tr>`;}).join('')}</tbody></table></div>`;}
function llRenderStandings(key=llTeamLeague(lexLeague.state.playerTeam)||'first'){llSetWide(true);llArea().innerHTML=`<div class="ll-shell"><div class="ll-panel"><div class="ll-topbar"><div><div class="ll-title">${llLeagueLabel(key)} <em>Tablosu</em></div><div class="ll-muted">Sezon ${lexLeague.state.season}</div></div><div class="ll-actions"><button class="ll-btn" onclick="llRenderStandings('${key==='super'?'first':'super'}')">${llLeagueLabel(key==='super'?'first':'super')}</button><button class="ll-btn" onclick="llRenderDashboard()">← Dashboard</button></div></div>${llTableHtml(key)}</div></div>`;}
function llV2RewardTable(){return `<div class="ll-card"><div class="ll-card-title">AP / LP Ödülleri</div><div class="ll-table-wrap"><table class="ll-table" style="min-width:520px"><thead><tr><th>Organizasyon</th><th>Doğru AP</th><th>Galibiyet LP</th><th>Beraberlik LP</th><th>Mağlubiyet LP</th></tr></thead><tbody>${[['Lig',LL_COMP_REWARDS.league],['Türkiye Kupası',LL_COMP_REWARDS.cup],['Play-Off',LL_COMP_REWARDS.playoff],['Şampiyonlar Ligi',LL_COMP_REWARDS.ucl],['Avrupa Ligi',LL_COMP_REWARDS.uel],['Konferans Ligi',LL_COMP_REWARDS.uecl]].map(([n,r])=>`<tr><td>${n}</td><td>${r.ap}</td><td>${r.win}</td><td>${r.draw}</td><td>${r.loss}</td></tr>`).join('')}</tbody></table></div></div>`;}
function llRenderDashboard(){
  const s=lexLeague.state;if(!s){renderLexiconLeagueLanding();return;}if(s.seasonEnded){llRenderSeasonEnd();return;}lexLeague.active=true;llSetWide(true);llClearTransient();llV2EnsureSpecial();
  const f=llPlayerFixture();if(!f){llCompleteSeason();return;}const key=llTeamLeague(s.playerTeam),team=llTeamState(s.playerTeam),def=llTeamDef(s.playerTeam),oppName=f.home===s.playerTeam?f.away:f.home,opp=llTeamState(oppName),oppDef=llTeamDef(oppName),comp=f.competition||'league';
  const compLabel=comp==='league'?llLeagueLabel(key):comp==='cup'?'Ziraat Türkiye Kupası':comp==='playoff'?'1. Lig Play-Off':comp==='ucl'?'Şampiyonlar Ligi':comp==='uel'?'Avrupa Ligi':'Konferans Ligi';
  llArea().innerHTML=`<div class="ll-shell"><div class="ll-panel"><div class="ll-topbar"><div class="ll-brand"><div class="ll-brand-mark">${llTeamLogo(def,'brand')}</div><div><div class="ll-title">${llEscape(s.playerTeam)}</div><div class="ll-muted">Sezon ${s.season} · ${llLeagueLabel(key)} · ${s.week}. hafta</div></div></div><div class="ll-actions"><button class="ll-btn" onclick="llRenderStandings('${key}')">Lig Tablosu</button><button class="ll-btn" onclick="llRenderStandings('${key==='super'?'first':'super'}')">Diğer Lig</button>${[10,20,30].includes(s.week)&&comp==='league'?'<button class="ll-btn gold" onclick="llRenderShop()">Transfer Merkezi</button>':''}<button class="ll-btn" onclick="llGoMainMenu()">Ana Menü</button></div></div><div class="ll-metrics"><div class="ll-metric"><strong>${s.ap}</strong><span>AP</span></div><div class="ll-metric"><strong>${s.lp}</strong><span>LP</span></div><div class="ll-metric"><strong>${llStars(team.stars)}</strong><span>Yıldız</span></div><div class="ll-metric"><strong>${llSortTable(key).findIndex(x=>x.team===s.playerTeam)+1}.</strong><span>Sıra</span></div></div><div class="ll-grid"><div><div class="ll-card"><div class="ll-card-title">${compLabel} · ${f.roundLabel||''}</div><div class="ll-next-match"><div class="ll-club"><div class="ll-club-icon">${llTeamLogo(def,'match')}</div><b>${llEscape(s.playerTeam)}</b></div><div class="ll-vs">VS</div><div class="ll-club"><div class="ll-club-icon">${llTeamLogo(oppDef,'match')}</div><b>${llEscape(oppName)}</b></div></div><button class="ll-btn primary" style="width:100%;margin-top:13px" onclick="llStartMatchPreparation()">10 Kelimelik Maça Başla</button></div><div class="ll-card" style="margin-top:12px"><div class="ll-card-title">Kadro ve Yetenekler</div><div class="ll-squad">${LL_POSITIONS.map(pos=>`<div class="ll-slot"><div class="ll-slot-head"><span class="ll-position">${LL_POSITION_ICONS[pos]} ${pos}</span><span class="ll-die-mini star${Math.min(team.stars,3)}">${llRangeText(team.stars)}</span></div>${llCardHtml(team.cards[pos],s.playerTeam)}</div>`).join('')}</div><button class="ll-btn" style="width:100%;margin-top:12px" ${team.stars>=5?'disabled':''} onclick="llUpgradeStars()">${team.stars>=5?'Maksimum 5 yıldız':`Yıldızı Yükselt · ${llV2UpgradeCost(team.stars)} LP`}</button></div>${llV2RewardTable()}</div><div>${llTableHtml(key)}</div></div></div></div>`;
}

function llFinishLeagueQuiz(){const q=lexLeague.quiz;if(!q||q.committed)return;q.committed=true;const comp=llPlayerFixture()?.competition||'league',reward=LL_COMP_REWARDS[comp]||LL_COMP_REWARDS.league,ap=q.correct*reward.ap;lexLeague.state.ap+=ap;let bonus='none';if(q.correct===10){bonus='perfect';lexLeague.state.lp+=10;}else if(q.correct===9)bonus='reroll';q.apEarned=ap;q.reward=bonus;llSave();llRenderQuizReward();}
function llRecordMatch(home,away,hg,ag,week,userMatch=false,competition='league',league=null){if(competition==='league'){llUpdateStanding(home,hg,ag);llUpdateStanding(away,ag,hg);[[home,hg,ag],[away,ag,hg]].forEach(([n,gf,ga])=>{if(n===lexLeague.state.playerTeam)return;const t=llTeamState(n);t.aiAp=(t.aiAp||0)+(gf>ga?20:gf===ga?12:6);});}lexLeague.state.results.push({season:lexLeague.state.season,week,home,away,homeGoals:hg,awayGoals:ag,userMatch,competition,league});}
function llV2SimFixture(f,competition='league',league=null,week=lexLeague.state.week){const sim=llSimulateMatch(f.home,f.away);llRecordMatch(f.home,f.away,sim.homeGoals,sim.awayGoals,week,false,competition,league);llApplyLocks(sim.resolution,f.home,f.away);return sim.homeGoals===sim.awayGoals?(Math.random()<.5?f.home:f.away):sim.homeGoals>sim.awayGoals?f.home:f.away;}
function llV2PlayLeagueWeek(key,skipFixture){const round=lexLeague.state.schedules[key]?.[lexLeague.state.week-1]||[];round.filter(f=>!skipFixture||!(f.home===skipFixture.home&&f.away===skipFixture.away)).forEach(f=>llV2SimFixture(f,'league',key));}
function llCommitCurrentMatch(){
  const m=lexLeague.match;if(!m||m.committed||!m.resolution)return;m.committed=true;const s=lexLeague.state,f=m.fixture,comp=f.competition||'league',r=m.resolution,hg=m.playerHome?r.scoreA:r.scoreB,ag=m.playerHome?r.scoreB:r.scoreA,pg=r.scoreA,og=r.scoreB,reward=LL_COMP_REWARDS[comp]||LL_COMP_REWARDS.league;
  const lp=pg>og?reward.win:pg===og?reward.draw:reward.loss;s.lp+=lp;llRecordMatch(f.home,f.away,hg,ag,s.week,true,comp,f.league||null);llApplyLocks(r,m.player,m.opponent);
  let winner=pg===og?(Math.random()<.5?m.player:m.opponent):pg>og?m.player:m.opponent;
  if(comp==='league'){llV2PlayLeagueWeek('super',f.league==='super'?f:null);llV2PlayLeagueWeek('first',f.league==='first'?f:null);llDevelopOpponents(s.week);s.week++;}
  else if(comp==='cup')llV2FinishCupRound(winner);
  else if(['ucl','uel','uecl'].includes(comp))llV2FinishEuropeRound(winner);
  else if(comp==='playoff')llV2FinishPlayoffMatch(winner);
  s.pendingFixture=null;llSave();llRenderRoundSummary(s.week-(comp==='league'?1:0),lp,pg,og,comp,winner===m.player);
}
function llRenderRoundSummary(completedWeek,lp,pg,og,comp='league',advanced=false){const label=comp==='league'?'Lig':comp==='cup'?'Türkiye Kupası':comp==='playoff'?'Play-Off':comp.toUpperCase(),result=pg>og?'Galibiyet':pg===og?'Beraberlik':'Mağlubiyet';llArea().innerHTML=`<div class="ll-shell"><div class="ll-panel" style="text-align:center"><div class="quiz-start-title">${label} · ${result} <em>${pg}-${og}</em></div><div class="ll-notice">+${lp} LP${comp!=='league'&&pg===og?` · Penaltılar: ${advanced?'Tur atladın':'Elendin'}`:''}</div><button class="ll-btn primary" style="margin-top:16px" onclick="llRenderDashboard()">Devam Et</button></div></div>`;}

function llV2InitCup(state){
  const domestic=llShuffle([...state.leagues.super,...state.leagues.first]),preliminary=domestic.slice(0,12),byes=domestic.slice(12),field=[...preliminary,...byes.flatMap(team=>[team,null])];
  state.cup={round:0,field,alive:true,winner:null,pending:null};
}
function llV2EnsureSpecial(){const s=lexLeague.state;if(s.pendingFixture||s.seasonEnded)return;if(s.playoff){llV2EnsurePlayoff();return;}llV2EnsureCup();if(s.pendingFixture)return;llV2EnsureEurope();}
function llV2EnsureCup(){const s=lexLeague.state,c=s.cup;if(!c||c.round>=LL_CUP_WEEKS.length||s.week<LL_CUP_WEEKS[c.round]||c.pending)return;const next=[];let playerPair=null;for(let i=0;i<c.field.length;i+=2){const a=c.field[i],b=c.field[i+1];if(!a&&!b)continue;if(!a||!b){next.push(a||b);continue;}if(a===s.playerTeam||b===s.playerTeam){playerPair=[a,b];continue;}next.push(llV2SimFixture({home:a,away:b},'cup'));}if(playerPair){c.pending={next,pair:playerPair};s.pendingFixture={home:playerPair[0],away:playerPair[1],competition:'cup',roundLabel:LL_CUP_ROUNDS[c.round]};}else{c.field=next;c.round++;if(c.field.length===1){c.winner=c.field[0];c.alive=false;}}}
function llV2FinishCupRound(winner){const c=lexLeague.state.cup;if(!c?.pending)return;c.pending.next.push(winner);c.field=c.pending.next;c.pending=null;c.round++;if(winner!==lexLeague.state.playerTeam)c.alive=false;if(c.field.length===1){c.winner=c.field[0];if(c.winner===lexLeague.state.playerTeam)lexLeague.state.trophies.push({season:lexLeague.state.season,name:'Ziraat Türkiye Kupası'});}}
function llV2EnsureEurope(){const s=lexLeague.state,e=s.europe;if(!e||!e.alive||e.round>=LL_EURO_WEEKS.length||s.week<LL_EURO_WEEKS[e.round]||e.pending)return;const pool=llShuffle(UCL_TEAMS.filter(t=>t.name!==s.playerTeam)),opp=pool[e.round%pool.length];if(!s.teams[opp.name])s.teams[opp.name]={name:opp.name,stars:opp.pot===1?5:opp.pot===2?4:3,cards:{'Kaleci':null,'Orta Saha':null,'Forvet':null},lastResults:[],wins:0,lockedDice:{},aiAp:0,nextMatchRerolls:0,sixStreaks:{},nextMatchBonuses:{}};e.pending=opp.name;s.pendingFixture={home:e.round%2?s.playerTeam:opp.name,away:e.round%2?opp.name:s.playerTeam,competition:e.type,roundLabel:LL_EURO_ROUNDS[e.round]};}
function llV2FinishEuropeRound(winner){const e=lexLeague.state.europe;if(!e)return;e.pending=null;if(winner!==lexLeague.state.playerTeam){e.alive=false;return;}e.round++;if(e.round>=LL_EURO_ROUNDS.length){e.winner=lexLeague.state.playerTeam;e.alive=false;lexLeague.state.trophies.push({season:lexLeague.state.season,name:e.type==='ucl'?'UEFA Şampiyonlar Ligi':e.type==='uel'?'UEFA Avrupa Ligi':'UEFA Konferans Ligi'});}}

function llV2FinishRemainingLeague(){const s=lexLeague.state;for(const key of ['super','first'])for(let w=0;w<s.schedules[key].length;w++){const round=s.schedules[key][w];if(round.every(f=>s.results.some(r=>r.season===s.season&&r.competition==='league'&&r.home===f.home&&r.away===f.away)))continue;round.forEach(f=>llV2SimFixture(f,'league',key,w+1));}}
function llV2AiPlayoffWinner(rows){const win=(a,b)=>llV2SimFixture({home:a,away:b},'playoff');const q1=win(rows[3].team,rows[6].team),q2=win(rows[4].team,rows[5].team),sf=win(q1,q2);return win(rows[2].team,sf);}
function llCompleteSeason(){const s=lexLeague.state;llV2FinishRemainingLeague();const first=llSortTable('first'),pos=first.findIndex(r=>r.team===s.playerTeam)+1;if(llTeamLeague(s.playerTeam)==='first'&&pos>=3&&pos<=7){llV2StartPlayerPlayoff(first,pos);llSave();llRenderDashboard();return;}llV2FinalizeSeason(llV2AiPlayoffWinner(first));}
function llV2StartPlayerPlayoff(rows,pos){const s=lexLeague.state,seed3=rows[2].team,q1=[rows[3].team,rows[6].team],q2=[rows[4].team,rows[5].team];s.playoff={seed3,stage:null,other:null};if(pos===3){const w1=llV2SimFixture({home:q1[0],away:q1[1]},'playoff'),w2=llV2SimFixture({home:q2[0],away:q2[1]},'playoff'),sf=llV2SimFixture({home:w1,away:w2},'playoff');s.playoff.stage='final';s.playoff.opponent=sf;}else{const mine=q1.includes(s.playerTeam)?q1:q2,other=mine===q1?q2:q1;s.playoff.other=llV2SimFixture({home:other[0],away:other[1]},'playoff');s.playoff.stage='qf';s.playoff.opponent=mine.find(n=>n!==s.playerTeam);}}
function llV2EnsurePlayoff(){const s=lexLeague.state,p=s.playoff;if(!p||s.pendingFixture)return;s.pendingFixture={home:s.playerTeam,away:p.opponent,competition:'playoff',roundLabel:p.stage==='qf'?'Play-Off 1. Tur':p.stage==='sf'?'Play-Off Yarı Final':'Play-Off Final'};}
function llV2FinishPlayoffMatch(winner){const s=lexLeague.state,p=s.playoff;if(winner!==s.playerTeam){const aiWinner=p.stage==='final'?p.opponent:p.stage==='sf'?llV2SimFixture({home:p.opponent,away:p.seed3},'playoff'):llV2SimFixture({home:llV2SimFixture({home:p.opponent,away:p.other},'playoff'),away:p.seed3},'playoff');s.playoff=null;llV2FinalizeSeason(aiWinner);return;}if(p.stage==='qf'){p.stage='sf';p.opponent=p.other;}else if(p.stage==='sf'){p.stage='final';p.opponent=p.seed3;}else{s.playoff=null;llV2FinalizeSeason(s.playerTeam);}}
function llV2Qualifications(superRows,cupWinner){const q={ucl:[superRows[0].team,superRows[1].team],uel:[],uecl:[]},used=new Set(q.ucl);if(cupWinner&&!used.has(cupWinner)){q.uel.push(cupWinner);used.add(cupWinner);}for(const row of superRows){if(used.has(row.team))continue;if(q.uel.length<2){q.uel.push(row.team);used.add(row.team);}else if(q.uecl.length<2){q.uecl.push(row.team);used.add(row.team);}if(q.uecl.length===2)break;}return q;}
function llV2FinalizeSeason(playoffWinner){const s=lexLeague.state,superRows=llSortTable('super'),firstRows=llSortTable('first'),relegated=superRows.slice(-3).map(r=>r.team),promoted=[firstRows[0].team,firstRows[1].team,playoffWinner],qualifications=llV2Qualifications(superRows,s.cup?.winner);s.lastSeasonSummary={season:s.season,superRows,firstRows,relegated,promoted,playoffWinner,cupWinner:s.cup?.winner,qualifications,playerLeague:llTeamLeague(s.playerTeam),playerPosition:(llTeamLeague(s.playerTeam)==='super'?superRows:firstRows).findIndex(r=>r.team===s.playerTeam)+1};s.seasonEnded=true;llSave();llRenderSeasonEnd();}
function llRenderSeasonEnd(){const x=lexLeague.state.lastSeasonSummary;if(!x){llRenderDashboard();return;}llArea().innerHTML=`<div class="ll-shell"><div class="ll-panel"><div class="quiz-start-title">Sezon ${x.season} <em>Tamamlandı</em></div><div class="ll-metrics"><div class="ll-metric"><strong>${x.playerPosition}.</strong><span>Sıra</span></div><div class="ll-metric"><strong>${x.cupWinner||'—'}</strong><span>Türkiye Kupası</span></div><div class="ll-metric"><strong>${x.promoted.length}</strong><span>Yükselen</span></div><div class="ll-metric"><strong>${x.relegated.length}</strong><span>Düşen</span></div></div><div class="ll-grid"><div><div class="ll-card"><div class="ll-card-title">Süper Lig'den Düşenler</div><div class="ll-sub">${x.relegated.join(' · ')}</div></div><div class="ll-card" style="margin-top:12px"><div class="ll-card-title">Süper Lig'e Yükselenler</div><div class="ll-sub">${x.promoted.join(' · ')}</div></div></div>${llV2RewardTable()}</div><button class="ll-btn primary" style="margin-top:16px" onclick="llStartNextSeason()">Yeni Sezona Başla</button></div></div>`;}
function llStartNextSeason(){const s=lexLeague.state,x=s.lastSeasonSummary,superSet=new Set(s.leagues.super),firstSet=new Set(s.leagues.first);x.relegated.forEach(n=>{superSet.delete(n);firstSet.add(n);});x.promoted.forEach(n=>{firstSet.delete(n);superSet.add(n);});s.leagues={super:[...superSet],first:[...firstSet]};s.season++;s.week=1;s.seasonEnded=false;s.standings={super:llBlankStandings(s.leagues.super),first:llBlankStandings(s.leagues.first)};s.schedules={super:llGenerateSchedule(s.leagues.super),first:llGenerateSchedule(s.leagues.first)};s.pendingFixture=null;s.playoff=null;s.results=[];s.aiTransferWindows={};s.lastSeasonSummary=null;Object.values(s.teams).forEach(t=>{t.lastResults=[];t.wins=0;t.lockedDice={};});const type=x.qualifications.ucl.includes(s.playerTeam)?'ucl':x.qualifications.uel.includes(s.playerTeam)?'uel':x.qualifications.uecl.includes(s.playerTeam)?'uecl':null;s.europe=type?{type,round:0,alive:true,pending:null,winner:null}:null;llV2InitCup(s);llSave();llRenderDashboard();}
function llDevelopOpponents(completedWeek){const s=lexLeague.state;if(completedWeek<10)return;if(!s.aiTransferWindows)s.aiTransferWindows={};[10,20,30].filter(w=>completedWeek>=w&&!s.aiTransferWindows[`${s.season}-${w}`]).forEach(w=>{LL_ALL_TEAMS.map(t=>t.name).filter(n=>n!==s.playerTeam).forEach(n=>{const t=llTeamState(n);while(t.aiAp>=150){const r=llAiShopAttempt(n);if(!r.spent)break;}});s.aiTransferWindows[`${s.season}-${w}`]=true;});}
function llV2UpgradeCost(stars){return ({1:800,2:1400,3:2300,4:3500})[stars]||0;}
function llUpgradeStars(){const t=llTeamState(lexLeague.state.playerTeam),cost=llV2UpgradeCost(t.stars);if(!cost)return;if(lexLeague.state.lp<cost){alert(`Yetersiz LP. Gerekli: ${cost} LP`);return;}if(!confirm(`${cost} LP ile takımı ${t.stars+1} yıldıza yükseltmek istiyor musun?`))return;lexLeague.state.lp-=cost;t.stars++;llSave();llRenderDashboard();}
function llStartCareer(teamName){if(localStorage.getItem(LL_V2_SAVE_KEY)&&!confirm('Mevcut iki ligli kariyerin üzerine yeni kariyer yazılsın mı?'))return;lexLeague.state=llNewState(teamName);llAssignStarterCardsToAi();llSave();llRenderStarterShop();}
